### ISSUE TITLE
Feature request: While keypress continue nudging

### ISSUE THREAD

**Issue by piotrnikov** [bergamote/greaspencil_nudge_frames#2]
Hello and many thanks for this simple yet super useful addon!!!
I have a very small request if possible. Could there be an option for a continuous nudging as long as the keys are pressed?
It's a small thing but it would help me greatly :)
Thanks!

**Comment by bergamote** [comment]
Hi! Hmmm, will try to look into it but don't get your hopes up (since the code executes *before* the key is released I don't think I have a way of knowing when a key is down). As a workaround, after pressing D or F, press G to move the frames with the mouse/stylus?

**Comment by piotrnikov** [comment]
No worries and thanks! 
Pressing G is indeed, what I already do for un-subtle big moves :)

**Comment by bergamote** [comment]
Hi! Well, I know this was a while ago, but I looked into it again and turns out there's a way to do that through blender's keymap and it's crazy simple.  I updated the addon so now it works just like you'd said. But you can also go to Keymap in the preferences, search for *gp_frames* and tick the Repeat box in both results

**Comment by piotrnikov** [comment]
Thanks!!!!
